"""add workflow table

Revision ID: 8a1b2c3d4e5f
Revises: 69a096382fae
Create Date: 2026-01-25 10:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8a1b2c3d4e5f"
down_revision = "69a096382fae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["customer.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_index(
        op.f("ix_customer_workflow_project_id"),
        "workflow",
        ["project_id"],
        unique=False,
        schema="customer",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_workflow_project_id"),
        table_name="workflow",
        schema="customer",
    )
    op.drop_table("workflow", schema="customer")
    # ### end Alembic commands ###
